In [2]:
import numpy as np

+ Reverse a vector (first element becomes last)

In [5]:
a = np.arange(5)
a[::-1]

array([4, 3, 2, 1, 0])

+ Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

+ Find indices of non-zero elements from [3,2,0,0,4,0]

In [7]:
a = np.array([3,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

+ Create a 3x3x3 array with random values

In [8]:
np.random.rand(3,3,3)

array([[[0.87153389, 0.79934193, 0.3570833 ],
        [0.0954146 , 0.30376442, 0.44399606],
        [0.91632546, 0.98932897, 0.39992939]],

       [[0.66521894, 0.07364524, 0.61874437],
        [0.40066913, 0.80616255, 0.59080327],
        [0.06030618, 0.62760408, 0.73149202]],

       [[0.15535676, 0.71432495, 0.70266193],
        [0.18455275, 0.73172582, 0.81714631],
        [0.17132668, 0.83005458, 0.64577681]]])

+ Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
a = np.random.rand(10,10)
print('max is: {}'.format(a.max()))
print('min is: {}'.format(a.min()))

max is: 0.9763078566532611
min is: 0.019597959809146914


+ Create a 2d array with 1 on the border and 0 inside. Like:

In [14]:
a = np.ones((4,4))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

+ make two random arrays of integers from 0 to 3 of 3 elements and check if they are equal

In [17]:
a = np.random.randint(0,3,3)
b = np.random.randint(0,3,3)

all(a == b)

False

In [18]:
np.allclose(a,b)

False

+ Create random vector of size 10 and replace the maximum value by 0

In [19]:
a = np.random.rand(10)
a[a.argmax()] = 0
a

array([0.10327187, 0.3038906 , 0.52602426, 0.40614866, 0.22379021,
       0.49053635, 0.54542735, 0.0725447 , 0.        , 0.48420171])

+ Considering the following 10x3 matrix, extract rows with unequal values (e.g. [1,1,0]) 

In [3]:
a = np.ones((10,3), dtype=int)
i = np.random.randint(0,9,1)
j = np.random.randint(0,3,1)
a[i,j] = 0
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
a[np.nonzero(~np.all(a == 1, axis=1))]

array([[1, 1, 0]])